import AppKit
import ClipboardCore

final class PasteboardMonitor {
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"
    ]
    private let pasteboard: NSPasteboard
    private var changeCount: Int
    private var timer: Timer?
    var onCapture: ((ClipPayload, String) -> Void)?
    var isPaused = false {
        didSet { changeCount = pasteboard.changeCount }
    }

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        // Only collect new copies; do not read pre-launch clipboard contents.
        changeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in self?.poll() }
        timer.tolerance = 0.05
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func poll() {
        guard changeCount != pasteboard.changeCount else { return }
        changeCount = pasteboard.changeCount
        guard !isPaused else { return }
        let observedCount = changeCount
        guard let payload = Self.read(from: pasteboard), pasteboard.changeCount == observedCount else { return }
        onCapture?(payload, NSWorkspace.shared.frontmostApplication?.localizedName ?? "")
    }

    static func read(from pasteboard: NSPasteboard) -> ClipPayload? {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
            .union((pasteboard.pasteboardItems ?? []).flatMap { $0.types.map(\.rawValue) })
        guard types.isDisjoint(with: ignoredTypes) else { return nil }
        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            return .files(urls.map(\.absoluteString))
        }
        if let data = pasteboard.data(forType: .png), data.count <= 8 * 1024 * 1024,
           NSImage(data: data) != nil {
            return .image(data)
        }
        if let data = pasteboard.data(forType: .tiff), data.count <= 32 * 1024 * 1024,
           let bitmap = NSBitmapImageRep(data: data),
           let png = bitmap.representation(using: .png, properties: [:]), png.count <= 8 * 1024 * 1024 {
            return .image(png)
        }
        if let text = pasteboard.string(forType: .string), !text.isEmpty, text.utf8.count <= 8 * 1024 * 1024 {
            return .text(text)
        }
        return nil
    }

    @discardableResult
    func write(_ payload: ClipPayload) -> Bool {
        // Prepare representations before clearing the existing clipboard.
        let objects: [NSPasteboardWriting]
        switch payload {
        case .text(let text): objects = [text as NSString]
        case .image(let data):
            guard let image = NSImage(data: data), let tiff = image.tiffRepresentation else { return false }
            let item = NSPasteboardItem()
            item.setData(data, forType: .png)
            item.setData(tiff, forType: .tiff)
            objects = [item]
        case .files(let strings):
            let urls = strings.compactMap(URL.init(string:))
            guard !urls.isEmpty, urls.allSatisfy({ $0.isFileURL && FileManager.default.fileExists(atPath: $0.path) })
                else { return false }
            objects = urls.map { $0 as NSURL }
        }
        pasteboard.clearContents()
        let success = pasteboard.writeObjects(objects)
        changeCount = pasteboard.changeCount // Our write must not create another history entry.
        return success
    }

    deinit { timer?.invalidate() }
}
